
测试服务器：owl.acttao.com
部署过程中所遇问题：

问题--1: owl.acttao.com 执行python python manage.py supervisor restart all ，提示http：xxx.. refused connection.
解决过程：由于对supervisor的不熟悉，并认为是远程的sentry服务无法连接，而且restart 命令让我认为supervisor服务已经启动。后来想着手动启动一一个服务，才得知，supervisor服务没有启动。
解决方法:启动supervisor服务 
python manage.py supervisor start 

问题--2: 提示缺少某些字段，并且需要提示需要执行python manage.py compress 命令
解决过程：由于对loe的所用到的第三包还不熟悉，提示缺少字段，就初步认为是migrate没有做好，出了问题。 以及 静态文件的 collectstatic/compress 出现了问题。花费不少时间在查找解决方法，后面才得知，migrate 并不会将第三方翻译包的字段同步到数据库，而出现这个原因，是因为我重建了数据库（syncdb)。
解决方法：
python manage.py sync_translation_fields
python manage.py update_translation_fields

问题--3：网站登录出现502，sentry日志报错指向  doodoll_auth/utils.py ? in get_remote_user 
解决过程：因本地测试环境能够正常登录，以为是部署过程出现问题，后面一直找不到原因。
解决方法：owl自己恢复，又可以正常登录了。考虑是doodoll用户认证不稳定。

测试服务器 -- bjowl.acttao.com
问题 --1 ：问题--3：网站登录出现502，sentry日志报错指向  doodoll_auth/utils.py ? in get_remote_user 
解决方法：目前还未找到。
